Repository Brick-Studios/BrickEngine, pull requests merged in 2019-11, with the labels that each got.

#34 Added mouse support and ClickComponent
  include/brickengine/components/click_component.hpp
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
  lib/components/click_component.cpp
Labels: feature

#35 Fixed movement and deltatime
  include/brickengine/systems/physics_system.hpp
  lib/engine.cpp
  lib/systems/physics_system.cpp
Labels: bug

#37 Fixed bug where velocity wouldn't be reset by physics when collision occurs
  include/brickengine/systems/physics_system.hpp
  lib/systems/physics_system.cpp
Labels: bug, enhancement

#39 JSON & alpha
  include/brickengine/engine.hpp
  include/brickengine/extern/nlohmann_json.hpp
  include/brickengine/json/exceptions/no_path_exception.hpp
  include/brickengine/json/exceptions/no_valid_json_or_path_exception.hpp
  include/brickengine/json/exceptions/object_or_type_exception.hpp
  include/brickengine/json/json.hpp
  include/brickengine/rendering/renderable_factory.hpp
  include/brickengine/rendering/renderables/renderable.hpp
  include/brickengine/rendering/renderables/texture.hpp
  lib/CMakeLists.txt
  lib/components/renderables/texture_component.cpp
  lib/engine.cpp
  lib/json/json.cpp
  lib/rendering/renderable_factory.cpp
  lib/rendering/renderables/renderable.cpp
  lib/rendering/renderables/texture.cpp
  lib/rendering/renderer.cpp
  tests/CMakeLists.txt
  tests/assets/test.json
  tests/json_test.cpp
Labels: feature

#38 Added entity_manager tests (💯% 🔥🔥🔥)
  .gitignore
  CMakeLists.txt
  include/brickengine/entities/entity_manager.hpp
  lib/CMakeLists.txt
  tests/CMakeLists.txt
  tests/entities/entity_manager_test.cpp
  tests/int_test.cpp
Labels: enhancement

#41 Fix for building on MacOS
  CMakeLists.txt
  lib/rendering/renderable_factory.cpp
  lib/resource_manager.cpp
Labels: bug

#40 ECS parent-child, isTrigger and input delaying
  include/brickengine/collision_detector.hpp
  include/brickengine/components/colliders/rectangle_collider_component.hpp
  include/brickengine/components/data/position.hpp
  include/brickengine/components/data/scale.hpp
  include/brickengine/components/enums/kinematic.hpp
  include/brickengine/components/physics_component.hpp
  include/brickengine/components/transform_component.hpp
  include/brickengine/entities/entity_manager.hpp
  include/brickengine/entities/exceptions/grandparents_not_supported.hpp
  include/brickengine/input.hpp
  include/brickengine/systems/physics_system.hpp
  lib/collision_detector.cpp
  lib/components/colliders/rectangle_collider_component.cpp
  lib/components/physics_component.cpp
  lib/components/transform_component.cpp
  lib/systems/physics_system.cpp
  lib/systems/rendering_system.cpp
  tests/entities/entity_manager_parent_child_test.cpp
  tests/entities/entity_manager_test.cpp
Labels: feature, work in progress

#44 Collision caching, ECS tagging, component cloning and deltatime fix
  include/brickengine/collision_detector.hpp
  include/brickengine/components/colliders/rectangle_collider_component.hpp
  include/brickengine/components/player_component.hpp
  include/brickengine/components/renderables/texture_component.hpp
  include/brickengine/components/transform_component.hpp
  include/brickengine/entities/entity_manager.hpp
  include/brickengine/entities/exceptions/component_not_found.hpp
  include/brickengine/entities/exceptions/entity_id_not_found.hpp
  include/brickengine/entities/exceptions/entity_not_found.hpp
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
  include/brickengine/rendering/renderables/texture.hpp
  include/brickengine/systems/physics_system.hpp
  lib/collision_detector.cpp
  lib/components/colliders/rectangle_collider_component.cpp
  lib/components/player_component.cpp
  lib/components/renderables/texture_component.cpp
  lib/components/transform_component.cpp
  lib/rendering/renderables/texture.cpp
  lib/rendering/renderer.cpp
  lib/systems/physics_system.cpp
  lib/systems/rendering_system.cpp
  tests/entities/entity_manager_parent_child_test.cpp
  tests/entities/entity_manager_test.cpp
Labels: feature

#45 Added random
  include/brickengine/std/random.hpp
  lib/std/random.cpp
Labels: feature

#48 Controller support
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
  lib/engine.cpp
Labels: feature

#51 Improved controller detection
  include/brickengine/input.hpp
Labels: enhancement
