Repository Brick-Studios/BrickEngine, pull requests merged in 2019-10, with the labels that each got.

#15 Moved FPS Counter to engine
  include/brickengine/engine.hpp
  lib/engine.cpp
Labels: enhancement

#16 Changed Input to generic templating instead of enum hardcode
  include/brickengine/input.hpp
  include/brickengine/input/input.hpp
  include/brickengine/input/player_input.hpp
  lib/input/input.cpp
Labels: enhancement

#14 Added the base of the new ECS systems, physics and rendering
  cmake/sdl2/FindSDL2_image.cmake
  include/brickengine/components/component.hpp
  include/brickengine/components/component_impl.hpp
  include/brickengine/components/health_component.hpp
  include/brickengine/components/physics_component.hpp
  include/brickengine/components/player_component.hpp
  include/brickengine/components/renderable_component.hpp
  include/brickengine/components/renderables/texture_component.hpp
  include/brickengine/components/transform_component.hpp
  include/brickengine/engine.hpp
  include/brickengine/entities/entity_factory.hpp
  include/brickengine/entities/entity_manager.hpp
  include/brickengine/entities/entity_with_component.hpp
  include/brickengine/input.hpp
  include/brickengine/rendering/renderables/texture.hpp
  include/brickengine/systems/physics_system.hpp
  include/brickengine/systems/rendering_system.hpp
  include/brickengine/systems/system.hpp
  lib/CMakeLists.txt
  lib/components/physics_component.cpp
  lib/components/player_component.cpp
  lib/components/renderables/texture_component.cpp
  lib/components/transform_component.cpp
  lib/engine.cpp
  lib/rendering/renderable_factory.cpp
  lib/rendering/renderables/texture.cpp
  lib/rendering/renderer.cpp
  lib/systems/physics_system.cpp
  lib/systems/rendering_system.cpp
Labels: feature

#12 Added collision detection system
  include/brickengine/collision_detector.hpp
  include/brickengine/components/colliders/rectangle_collider_component.hpp
  include/brickengine/enum/axis.hpp
  include/brickengine/enum/direction.hpp
  include/brickengine/input.hpp
  include/brickengine/systems/physics_system.hpp
  lib/collision_detector.cpp
  lib/components/colliders/rectangle_collider_component.cpp
  lib/systems/physics_system.cpp
Labels: feature

#25 Adjusted gravity values
  include/brickengine/systems/physics_system.hpp
Labels: enhancement

#29 Fixed sanitizer not working, also added it to the test bin
  .github/workflows/main.yml
  CMakeLists.txt
  lib/CMakeLists.txt
  tests/CMakeLists.txt
Labels: bug

#28 Updated CI with tests and compilers
  .github/workflows/main.yml
  CMakeLists.txt
Labels: ci, work in progress

#32 Fixed building the engine on master
  .github/workflows/main.yml
Labels: ci

#31 Added Texture manager
  include/brickengine/engine.hpp
  include/brickengine/rendering/renderable_factory.hpp
  include/brickengine/rendering/renderables/texture.hpp
  include/brickengine/resource_manager.hpp
  lib/engine.cpp
  lib/rendering/renderable_factory.cpp
  lib/rendering/renderables/texture.cpp
  lib/resource_manager.cpp
Labels: feature
