Repository Brick-Studios/BrickEngine, pull requests merged in 2019-12, with the labels that each got.

#52 Small tag addition + fixed not using absolute transform
  include/brickengine/entities/entity_manager.hpp
  include/brickengine/entities/exceptions/child_already_has_parent_exception.hpp
  include/brickengine/exceptions/not_implemented_exception.hpp
  lib/collision_detector.cpp
Labels: enhancement

#49 Added page up and down input
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
  include/brickengine/systems/physics_system.hpp
  lib/systems/physics_system.cpp
Labels: work in progress

#59 Added entity exists function to EntityManager
  include/brickengine/entities/entity_manager.hpp
Labels: enhancement

#58 Collision Detector 2 © - 🧱🏃‍♂️🔥
  include/brickengine/collision_detector.hpp
  include/brickengine/collision_detector_2.hpp
  include/brickengine/components/colliders/rectangle_collider_component.hpp
  include/brickengine/components/enums/collision_detection_type.hpp
  include/brickengine/components/physics_component.hpp
  include/brickengine/entities/entity_manager.hpp
  include/brickengine/std/doubly_unordered_map.hpp
  include/brickengine/std/sign.hpp
  include/brickengine/systems/displacement_system.hpp
  include/brickengine/systems/physics_system.hpp
  lib/collision_detector.cpp
  lib/collision_detector_2.cpp
  lib/components/colliders/rectangle_collider_component.cpp
  lib/components/physics_component.cpp
  lib/systems/displacement_system.cpp
  lib/systems/physics_system.cpp
  tests/entities/entity_manager_test.cpp
Labels: enhancement

#56 Added JSON writing and FloatingPointComparer
  include/brickengine/json/json.hpp
  include/brickengine/scenes/data/entity_components.hpp
  include/brickengine/scenes/scene.hpp
  include/brickengine/scenes/scene_manager.hpp
  include/brickengine/std/floating_point_comparer.hpp
  lib/collision_detector_2.cpp
  lib/json/json.cpp
  lib/systems/displacement_system.cpp
  lib/systems/physics_system.cpp
Labels: enhancement

#61 Fixed hardcoded font in the engine
  include/brickengine/engine.hpp
  include/brickengine/rendering/renderable_factory.hpp
  lib/engine.cpp
  lib/rendering/renderable_factory.cpp
Labels: enhancement

#63 Animation system
  include/brickengine/components/animation_component.hpp
  include/brickengine/rendering/renderable_factory.hpp
  include/brickengine/rendering/renderables/texture.hpp
  lib/components/animation_component.cpp
  lib/rendering/renderable_factory.cpp
  lib/rendering/renderables/texture.cpp
  lib/systems/rendering_system.cpp
Labels: feature

#64 Added F keys
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
Labels: feature

#66 Pause for animation
  include/brickengine/systems/animation_system.hpp
  lib/systems/animation_system.cpp
  lib/systems/rendering_system.cpp
Labels: enhancement

#70 Added dpad bindings
  include/brickengine/input.hpp
  include/brickengine/input_keycode.hpp
Labels: feature

#69 Added Collision Detector 2 discrete and continuous team work
  include/brickengine/collision_detector_2.hpp
  include/brickengine/components/enums/collision_detection_type.hpp
  include/brickengine/components/physics_component.hpp
  include/brickengine/std/floating_point_comparer.hpp
  lib/collision_detector_2.cpp
  lib/systems/displacement_system.cpp
  lib/systems/physics_system.cpp
  tests/entities/entity_manager_test.cpp
Labels: bug

#72 Removed SDL2_net dependency
  .github/workflows/main.yml
  lib/CMakeLists.txt
Labels: enhancement
